# Generated by Django 5.2.4 on 2025-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_detail', models.TextField(max_length=1000)),
                ('created_by', models.CharField(max_length=100)),
                ('event_time', models.TimeField(auto_now_add=True)),
                ('event_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
